// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFRZJesRCzlgF2eWwrVlJWZe-rvgKRq-E',
    appId: '1:962262322639:web:a466a09ebc0992887e16ba',
    messagingSenderId: '962262322639',
    projectId: 'booktracker-2a643',
    authDomain: 'booktracker-2a643.firebaseapp.com',
    storageBucket: 'booktracker-2a643.firebasestorage.app',
    measurementId: 'G-HCJS1T8VZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn3_7qL2hV37VgUTGn5Haxs9JrognPJXc',
    appId: '1:962262322639:android:3839d11c23a4207c7e16ba',
    messagingSenderId: '962262322639',
    projectId: 'booktracker-2a643',
    storageBucket: 'booktracker-2a643.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPfrKG6KPY7vkvjjw67IBKa-nGI0ypQOY',
    appId: '1:962262322639:ios:0cee09e1bd4271ed7e16ba',
    messagingSenderId: '962262322639',
    projectId: 'booktracker-2a643',
    storageBucket: 'booktracker-2a643.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPfrKG6KPY7vkvjjw67IBKa-nGI0ypQOY',
    appId: '1:962262322639:ios:0cee09e1bd4271ed7e16ba',
    messagingSenderId: '962262322639',
    projectId: 'booktracker-2a643',
    storageBucket: 'booktracker-2a643.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFRZJesRCzlgF2eWwrVlJWZe-rvgKRq-E',
    appId: '1:962262322639:web:7e7204bdb991e7737e16ba',
    messagingSenderId: '962262322639',
    projectId: 'booktracker-2a643',
    authDomain: 'booktracker-2a643.firebaseapp.com',
    storageBucket: 'booktracker-2a643.firebasestorage.app',
    measurementId: 'G-MV3R2RJKZQ',
  );
}
